import Head from 'next/head'
import Image from 'next/image'
import { NFTStorage } from 'nft.storage'
import styles from '../styles/Home.module.css'

export default function Home() {
  const token = ''
  const client = new NFTStorage({token})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>nft.storage test</h1>
      </main>
    </div>
  )
}
